### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by lamuertepeluda** [ThrivingKings/animo.js#28]
Hi,

could you please add a *package.json* file for npm support so that it could be installed via npm ([see this issue](https://github.com/npm/npm/issues/7232))? Adding to npm registry would also be appreciated.

Thanks, BR

Vito

**Comment by ThrivingKings** [comment]
Hi Vito— I definitely think it should be added to bower but it doesn't make much sense to me to install animo as a node module.

**Comment by ThrivingKings** [comment]
```bower install animo```

**Comment by lamuertepeluda** [comment]
Well Daniel, that's true unless you're using build tools like webpack as I do (webpack is omnivore).  
And you can have your library published on *both* npm and bower (and anything else you like) without conflicts as jQuery does.

**Comment by ThrivingKings** [comment]
It's not ideal, but you can use bower components with webpack (https://webpack.github.io/docs/usage-with-bower.html). My hesitation is that animo _really isn't_ a node module so I don't like the idea of it being available there. Do you mind telling me a little about how you're hoping to use animo in your project? Are you just looking to expose animo to all of your components?

**Comment by ThrivingKings** [comment]
thought about it and you're right. no reason for it not to be available via npm as well. just merged your PR. thanks!

**Comment by lamuertepeluda** [comment]
great :+1: 

At the moment I'm working on a p.o.c. for a project, so not even a real project, for a mobile app based on Apache Cordova...

I was looking for something that would make easier to include great Animate.css animations with jQuery and having control of what's going on, and then I found this very useful library of yours... :)

I know I could've used bower for front-end deps and then perhaps add a "npm preinstall" script for downloading the bower deps first, set bower_dependencies path into my webpack config and so on, but npm is also fine for me. And as you said there is no reason for not making it available via npm. So thank you very much!

**Comment by ThrivingKings** [comment]
Cool! Sorry for the brief back and forth about it and best of luck!
